# .github/workflows/build-and-deploy.yml

name: Node.js Build and Deploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v3

            # a standard step for GitHub actions on Node
            # https://github.com/actions/setup-node
            - uses: actions/setup-node@v3
              with:
                  # update the Node version to meet your needs
                  node-version: 16
                  cache: npm

            - name: Build
              run: |
                  npm ci
                  npm run build
                  touch website/out/.nojekyll
            - name: Prepare for Github Pages
              if: ${{ github.event_name == 'push' }}
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./website/out

    deploy:
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
